[mypy]
python_version = 3.11
warn_unused_configs = True
warn_return_any = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_no_return = True
ignore_missing_imports = False
strict_optional = True
check_untyped_defs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
no_implicit_optional = True
show_error_codes = True
plugins = pydantic.mypy
exclude = (?x)(
    ^apps/frontend/|^apps/admin/
)

[mypy-tests.*]
disallow_untyped_defs = False
