"""API route modules."""

from . import (
    admin,
    admin_auth,
    admin_brand,
    admin_contacts,
    admin_diagnostics,
    admin_media,
    admin_leaderboards,
    admin_ranks,
    admin_payments,
    admin_rules,
    admin_shop,
    admin_users,
    auth,
    brand_public,
    events,
    payments,
    public,
    shop,
    users,
    websocket,
)

__all__ = [
    "admin",
    "admin_auth",
    "admin_brand",
    "admin_contacts",
    "admin_diagnostics",
    "admin_media",
    "admin_leaderboards",
    "admin_ranks",
    "admin_payments",
    "admin_rules",
    "admin_shop",
    "admin_users",
    "auth",
    "brand_public",
    "events",
    "payments",
    "public",
    "shop",
    "users",
    "websocket",
]
