"""add brand and seo settings tables

Revision ID: 202407060012
Revises: 202407060011
Create Date: 2024-07-06 00:12:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '202407060012'
down_revision = '202407060011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.Text(), nullable=False),
    sa.Column('tagline', sa.Text(), nullable=False),
    sa.Column('logo_url_light', sa.Text(), nullable=True),
    sa.Column('logo_url_dark', sa.Text(), nullable=True),
    sa.Column('favicon_url', sa.Text(), nullable=True),
    sa.Column('theme_primary', sa.String(length=7), nullable=False),
    sa.Column('theme_bg', sa.String(length=7), nullable=False),
    sa.Column('theme_surface', sa.String(length=7), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_settings'))
    )
    
    op.create_table('seo_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_title', sa.Text(), nullable=False),
    sa.Column('title_template', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.Column('canonical_base_url', sa.Text(), nullable=False),
    sa.Column('og_image_url', sa.Text(), nullable=True),
    sa.Column('twitter_handle', sa.String(length=50), nullable=True),
    sa.Column('robots_policy', sa.String(length=50), nullable=False),
    sa.Column('sitemap_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_settings'))
    )
    
    # Insert default records
    op.execute("""
        INSERT INTO brand_settings (id, site_name, tagline, theme_primary, theme_bg, theme_surface, updated_at)
        VALUES (1, 'AmzCraft', 'Experience the ultimate Minecraft adventure', '#46C93A', '#0B1A0B', '#112412', NOW())
        ON CONFLICT (id) DO NOTHING
    """)
    
    op.execute("""
        INSERT INTO seo_settings (id, default_title, title_template, meta_description, canonical_base_url, robots_policy, sitemap_enabled, updated_at)
        VALUES (1, 'AmzCraft', '%s | AmzCraft', 'Low-latency Minecraft with seasons, ranks, and live events.', 'https://amzcraft.xyz', 'index,follow', true, NOW())
        ON CONFLICT (id) DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seo_settings')
    op.drop_table('brand_settings')
    # ### end Alembic commands ###