"""add actor_role to audit_logs

Revision ID: 202407060011
Revises: 202407060010
Create Date: 2024-07-06 00:11:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '202407060011'
down_revision = '202407060010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor_role', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'actor_role')
    # ### end Alembic commands ###