"""add featured_image_url to events

Revision ID: 202407060013
Revises: 202407060012
Create Date: 2024-07-06 00:13:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '202407060013'
down_revision = '202407060012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('featured_image_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'featured_image_url')
    # ### end Alembic commands ###